### ISSUE TITLE
Git Gui crash on Mac OS Sierra

### ISSUE THREAD

**Issue by premekkoch** [git/git-scm.com#853]
On MacOS Sierra git gui crashes randomlywith this message:
``` 
2016-09-22 13:17:36.759 Wish[23615:1501726] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [0 nan]'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff7f0407bb __exceptionPreprocess + 171
        1   libobjc.A.dylib                     0x00007fff937ada2a objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff7f0bda65 +[NSException raise:format:] + 197
        3   QuartzCore                          0x00007fff84c09980 _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 152
        4   QuartzCore                          0x00007fff84c09af5 -[CALayer setPosition:] + 44
        5   QuartzCore                          0x00007fff84c0a14b -[CALayer setFrame:] + 644
        6   CoreUI                              0x00007fff8a9b0112 _ZN20CUICoreThemeRenderer26MakeOrUpdateScrollBarLayerEPK13CUIDescriptoraPP7CALayer + 1284
        7   CoreUI                              0x00007fff8a9ac317 _ZN20CUICoreThemeRenderer19CreateOrUpdateLayerEPK13CUIDescriptorPP7CALayer + 1755
        8   CoreUI                              0x00007fff8a92e4d1 _ZN11CUIRenderer19CreateOrUpdateLayerEPK14__CFDictionaryPP7CALayer + 175
        9   CoreUI                              0x00007fff8a931185 CUICreateOrUpdateLayer + 221
        10  AppKit                              0x00007fff7d675623 -[NSCompositeAppearance _callCoreUIWithBlock:options:] + 226
        11  AppKit                              0x00007fff7cd22a9d -[NSAppearance _createOrUpdateLayer:options:] + 76
        12  AppKit                              0x00007fff7cf9b143 -[NSScrollerImp _animateToRolloverState] + 274
        13  AppKit                              0x00007fff7cf5ab79 __49-[NSScrollerImp _installDelayedRolloverAnimation]_block_invoke + 673
        14  AppKit                              0x00007fff7ce21331 -[NSScrollerImp _doWork:] + 15
        15  Foundation                          0x00007fff80a3ec88 __NSFireDelayedPerform + 417
        16  CoreFoundation                      0x00007fff7efc0f44 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
        17  CoreFoundation                      0x00007fff7efc0bd3 __CFRunLoopDoTimer + 1075
        18  CoreFoundation                      0x00007fff7efc072a __CFRunLoopDoTimers + 298
        19  CoreFoundation                      0x00007fff7efb82f1 __CFRunLoopRun + 2081
        20  CoreFoundation                      0x00007fff7efb7874 CFRunLoopRunSpecific + 420
        21  HIToolbox                           0x00007fff7e557f6c RunCurrentEventLoopInMode + 240
        22  HIToolbox                           0x00007fff7e557ca9 ReceiveNextEventCommon + 184
        23  HIToolbox                           0x00007fff7e557bd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
        24  AppKit                              0x00007fff7cc4e5f5 _DPSNextEvent + 1093
        25  AppKit                              0x00007fff7d35e8eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
        26  Tk                                  0x00000001047cc285 TkGenerateButtonEvent + 494
        27  Tk                                  0x00000001047cc54d Tk_MacOSXSetupTkNotifier + 395
        28  Tcl                                 0x00000001048be5a8 Tcl_DoOneEvent + 237
        29  Tk                                  0x0000000104726f4f Tk_MainLoop + 33
        30  Tk                                  0x0000000104732a5b Tk_MainEx + 1566
        31  Wish                                0x000000010470d55a Wish + 9562
        32  libdyld.dylib                       0x00007fff94089255 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
error: git-gui died of signal 6
```

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by premekkoch** [comment]
I'm sorry, thanks for info.

**Comment by bxt** [comment]
@premekkoch Did you report this to the mailing list? I have this problem too after updating to Sierra, but I can't find anything in their archives.

**Comment by c4mb0t** [comment]
@bxt I think I fixed it with this:
```
git config --local --unset gui.geometry
```

**Comment by fusillicode** [comment]
Unfortunately it is not 😔

**Comment by kjmph** [comment]
Not a git issue. Try:

```open /System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Wish.app```

Then, attempt to resize the console. This is internal to Apple.

**Comment by sieren** [comment]
@kjmph I'd assume on https://bugreport.apple.com

**Comment by sieren** [comment]
If you have Tk v8.4 lying around, it's worth trying to replace the Wish executable within Git with an older Wish version:

``` 
cp /System/Library/Frameworks/Tk.framework/Versions/8.4/Resources/Wish.app/Contents/MacOS/Wish /usr/local/Cellar/git/2.10.1/share/git-gui/lib/Git Gui.app/Contents/MacOS/
```

This seems to have worked around the crashes on my end.

`gitk` seems to use the `wish` executable defined in `$PATH` so you might need to bend that to the 8.4 version.

**Comment by mrTable** [comment]
@sieren, did the look of the git gui changed after replacing the Wish executable to 8.4? Mine has, looked really ugly and stretched.

**Comment by sieren** [comment]
It changed, yeah. However it doesnt look stretched, just an ugly old-school look here.

**Comment by djui** [comment]
Maybe you applied http://retinizer.mikelpr.com once and that it got overridden is back to normal/"ugly".

**Comment by mrTable** [comment]
Nope, never did that. 
It really does look like it got "unretinized" though.

**Comment by ssahu** [comment]
Instead of using the default MacOS tcl-tk, use the latest tcl-tk from homebrew and then link it by force.
`brew install tcl-tk`
`brew link tcl-tk --force`

**Comment by brooksbell** [comment]
I"m not using this client but we've encountered this call stack on Sierra.  In an NSScrollView the scroll bar is normally hidden until you mouse over it and even then only is shown if there is the potential for scrolling.  We had a NSScroller that was always visible (modernized code) and if no scroll was possible moving the mouse over it resulted in a NaN value being sent to the NSScroller.  The fix was to subclass NSScroller - then the NaN is not sent.

**Comment by djui** [comment]
Ran `brew install tcl-tk && brew link tcl-tk --force` and still got: `2016-10-19 11:12:51.367 Wish[75532:5137867] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 0]'`.

**Comment by djui** [comment]
As a workaround to me this seem to work (until I update git and then have to rerun it):

```
## Install newer Tcl/Tk version
brew install tcl-tk
brew link tcl-tk --force

## Your milage may vary
#git_version=$(brew info git --json=v1 | jq -r '.[].linked_keg')
git_version=2.10.1

## Make `git gui` use newer Tcl/Tk version
ln -s --backup=numbered $(which wish) "/usr/local/Cellar/git/$git_version/share/git-gui/lib/Git Gui.app/Contents/MacOS/Wish"
```

**Comment by kjmph** [comment]
Thank you! I had to do the following, and now gitk works for me:

```
brew uninstall --force git
brew install homebrew/dupes/tcl-tk
brew link tcl-tk --force
brew install git
```

Note, I have never had success with Apple bug reports, maybe someone with more clout can open the ticket?

**Comment by djui** [comment]
@kjmph interesting, are you saying that `brew install git` picks up the `brew install tcl-tk`'s path? Iff, that would be even easier.

**Comment by bxt** [comment]
@djui It seems like it does for `gitk` but not for `git gui`, because this one comes with its own bundled copy of `Wish`.

**Comment by kjmph** [comment]
@bxt is correct, gitk works, git gui still fails. I see why both fixes are required now.

**Comment by djui** [comment]
@bxt @kjmph OK. Not optimal, but finally having a temporary fix is great.

**Comment by Blahartinger** [comment]
so this only fixes gitk..not git gui? Or am I missing something for a workaround that fixes git gui?

**Comment by djui** [comment]
https://github.com/git/git-scm.com/issues/853#issuecomment-254768237 "solves" git gui. https://github.com/git/git-scm.com/issues/853#issuecomment-254821097 "solves" gitk.

**Comment by Blahartinger** [comment]
ahhh, I missed an error running with --backup=numbered . --backup isn't valid for the default mac ln util and the path already existed. Renamed the existing Wish bundled with git-gui and I'm all good now!

**Comment by garth** [comment]
After updating to git 2.10.2 I had to repeat the [above](https://github.com/git/git-scm.com/issues/853#issuecomment-254768237) instructions as well as making the following change.

edit `/usr/local/Cellar/git/2.10.2/libexec/git-core/git-gui` and set the libdir (line 7) to

```
    libdir="/usr/local/Cellar/git/2.10.2/share/git-gui/lib"
```

**Comment by djui** [comment]
@garth That the `@@HOMEBREW_PREFIX@@` template variable is not replace looks like (i) unrelated to this issue and (ii) like a regression. Wondering what happened? I can't directly see the issue in the Formular, if it wasn't in the bottle.

**Comment by garth** [comment]
@djui I wasn't sure if it was related to upgrading an installation that had to be hacked a little to get it working on Sierra. Hopefully these early issues with Sierra will be resolved soon and we can revert to a clean install. Until then we need somewhere to openly share these temporary workarounds.

**Comment by matt-jarrett** [comment]
This has been so frustrating.  I've tried following some of the fixes above but none worked for me.  Is there a consensus for a set of steps that should get me fixed so I can use `git gui`?  Thanks!

**Comment by bxt** [comment]
Have you tried [@djui's workaround above](https://github.com/git/git-scm.com/issues/853#issuecomment-254768237)? Seems to work for me. Maybe double check that you actually run the `git gui` for which you override the `Wish` bin (check version numbers etc). Also make sure you have a working `Wish` somewhere. Replace `$(which wish)` in the command with the path to the `Wish` you want to use. You could also get one from e.g. ActiveTcl if you don't use brew.

**Comment by Rotonen** [comment]
`brew link --force tcl-tk` actually fails with `the_platinum_searcher` installed as `bin/pt` collides.

This one would fundamentally be on Apple to fix. What do they actually ship their Tcl/Tk for? Is that community not hitting this one?

**Comment by djui** [comment]
@Rotonen Not a real help for Tcl problems, but if you want to try out something new, Rust instead of Go, have a look at [ripgrep](https://github.com/BurntSushi/ripgrep) (`rg`).

**Comment by Thierry46** [comment]
Hello everybody,
This exception on Mac OSX Sierra
... 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 0]'
can now be solved by upgrading to the lastest Mac OS version available on Applestore : Mac OS 10.12.2.
Best regards Thierry.

**Comment by kubark42** [comment]
> ... upgrading to the lastest Mac OS version available on Applestore : Mac OS 10.12.2.

Confirmed that this works for me as well. Thanks @Thierry46 for posting your experience here and letting us know to look at 10.12.2.

**Comment by iDVB** [comment]
@Thierry46 I'm running 10.12.2 uninstalled/installed both the .dmg and the homebrew versions and still get this issue. There must be more to this.... :(

**Comment by Rotonen** [comment]
@iDVB 

http://stackoverflow.com/questions/39833961/git-gui-crashes-on-mac-os-x-sierra/40974770#40974770

This is what I'm currently doing to remedy this in case of a broken TCL/TK installation.

But as stated, this was already fixed Apple-side.

**Comment by iDVB** [comment]
I ended up fixing the issue but I have no idea why it helped. I stumbled on the fix when I noticed that git gui only seemed to crash on one of my repos. I deleted the directory and re-cloned it. FIXED.

Only thing I can think of is that some marbles got lost when I switched the origin remote part way thru and the parent directory name was different.

**Comment by xbeta** [comment]
> @bxt I think I fixed it with this:
> 
> ```
> git config --local --unset gui.geometry
> ```
> Edit: Nope, never mind

This works for me
